version: '3'
services:
  migration:
    image: migrations:latest
    env_file:
      - .env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MIGRATION_DIR=/app/datasource
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_ADDR=${VAULT_ADDR}
    depends_on:
      - vault
      - redis
    networks:
      - backend
    volumes:
      - ../datasource:/app/datasource
    entrypoint: sh -c "sh scripts/provision-dev.sh && ./migrations && sh scripts/provision-mysql.sh"
    deploy:
      replicas: 1
      restart_policy:
        condition: none
  user:
    image: user:latest
    env_file:
      - .env
    ports:
      - "${USER_PORT}:${USER_PORT}"
    restart: always
    networks:
      - backend
      - frontend
  blacklist:
    image: blacklist:latest
    env_file:
      - .env
    ports:
      - "${BLACKLIST_PORT}:${BLACKLIST_PORT}"
    restart: always
    networks:
      - backend
  redis:
    image: redis:7.0.11
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
    networks:
      - backend
  vault:
    image: vault:1.7.3
    env_file:
      - .env
    ports:
      - 8200:8200
    depends_on:
      - mysql 
    environment:
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
    networks:
      - backend
    container_name: artifacts_vault_1
    volumes:
      - ./vault:/vault/config
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: artifacts_mysql_1

networks:
  backend:
  frontend: