version: '3'
services:
  migration:
    image: migrations:latest
    env_file:
      - .env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MIGRATION_DIR=/app/datasource
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_ADDR=${VAULT_ADDR}
    depends_on:
      - vault
    networks:
      - back
    volumes:
      - ../datasource:/app/datasource
    entrypoint: sh -c "sh scripts/provision-vault.sh && ./migrations"
    deploy:
      replicas: 1
      restart_policy:
        condition: none
  server:
    image: server:latest
    env_file:
      - .env
    environment:
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_ADDR=${VAULT_ADDR}
      - SYSTEM_TYPE
    ports:
      - "8080:8080"
    depends_on:
      - migrations
      - vault
    restart: always
    networks:
      - back
      - front
  vault:
    image: vault:1.7.3
    env_file:
      - .env
    ports:
      - 8200:8200
    depends_on:
      - mysql 
    environment:
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
    networks:
      - back
    container_name: artifacts_vault_1
    #volumes:
    #  - ./vault:/vault/config
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    networks:
      - back
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: artifacts_mysql_1

networks:
  back:
  front: